### ISSUE TITLE
Could not find a local of global install of a compatible fantomas-tool

### ISSUE THREAD

**Issue by AxelJunker** [nojaf/fantomas-for-rider#3]
I get

```
No compatible tool was found
Could not find a local of global install of a compatible fantomas-tool. Please read the documentation for more details.
```

when formatting an F# file.

Rider 2021.3.3
Fantomas 4.6.0-alpha-004 (tried installing both locally and globally)

**Comment by nojaf** [comment]
Can you run `fantomas --version` from the command line?

What does `dotnet tool list` and `dotnet tool list -g` output?

Could you try again with the latest version `4.6.3`?

**Comment by AxelJunker** [comment]
`fantomas --version`
Fantomas v4.6.0-alpha-004+db3dc672e5ca5d8becefc0559e0c76bcd8d44e19

`dotnet tool list`
fantomas-tool            4.6.0-alpha-004

`dotnet tool list -g`
fantomas-tool            4.6.0-alpha-004

Same with `4.6.3`, just tried it.

**Comment by nojaf** [comment]
Hmm, interesting. What operating system are you on?
I see something should be added to the log:
https://github.com/nojaf/fantomas-for-rider/blob/5bcfbcab3cb081511d61ce298a7fa05c10500fdd/src/rider/main/kotlin/com/nojaf/rider/plugins/fantomas/FormatCodeAction.kt#L79

Could you open the log file at:
![image](https://user-images.githubusercontent.com/2621499/153175985-fc5c6c81-b960-4c63-900d-a77cee4638c7.png)

There might be something in the main log or in the `Fantomas` subfolder. I'm not entirely sure anymore where it will be.

**Comment by AxelJunker** [comment]
I'm using macOS 12.2.

The log file didn't output anything when I ran your plugin.

The only fantomas related folder I could find was in `$HOME/.dotnet/tools/.store/fantomas-tool` but there are no log files there. That folder contains the global fantomas installation, not sure where the local installation is located. The [docs](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools) just say `The [local] tool binaries are installed in a default directory.`

PS. Thanks for your help!

**Comment by AxelJunker** [comment]
I was wrong, the log outputs:

```
2022-02-09 13:29:58,594 | DEBUG | RiderFileBreadcrumbsCollector  | backend breadcrumbs support handles file = true
2022-02-09 13:29:58,594 | DEBUG | RiderFileBreadcrumbsCollector  | start computing crumbs for the file file:///Users/junker/code/work/workflows/Shared/FileStorage.fs and offset 932
2022-02-09 13:29:58,596 | DEBUG | RiderFileBreadcrumbsCollector  | Have gotten crumbs from the backend: []
2022-02-09 13:29:59,252 | DEBUG | RiderFileBreadcrumbsCollector  | backend breadcrumbs support handles file = true
2022-02-09 13:29:59,253 | DEBUG | RiderFileBreadcrumbsCollector  | start computing crumbs for the file file:///Users/junker/code/work/workflows/Shared/FileStorage.fs and offset 933
2022-02-09 13:29:59,255 | DEBUG | RiderFileBreadcrumbsCollector  | Have gotten crumbs from the backend: []
```

But that only happened one of the times when I ran your plugin, so not sure if it's related.

**Comment by nojaf** [comment]
Hmm, ok those logs look unrelated.
Is `dotnet` available on your PATH?

Could you show me the full output of  `dotnet tool list`?

**Comment by nojaf** [comment]
Oh and do you see anything in the `Event Log` when the pop-up error shows?

**Comment by AxelJunker** [comment]
`dotnet` is available on my PATH

`dotnet tool list`:

<table>
<tr>
	<td>Package Id
	<td>Version
	<td>Commands
	<td>Manifest
<tr>
	<td>fantomas-tool
	<td>4.6.3
	<td>fantomas
	<td>/Users/junker/code/work/workflows/.config/dotnet-tools.json
</table>

I see the same error message as in my first post in the Event Log.

**Comment by nojaf** [comment]
Ok, at this point I have really no idea anymore.
Did you try restarting Rider since you've made any changes like installing a different version?

**Comment by AxelJunker** [comment]
Yeah, I did restart a couple of times when installing the newest version. Also tried only local install and only global install.

No worries, thank you for your help!

**Comment by nojaf** [comment]
I have some time on Friday, we could jump on a short call on our [Discord](https://discord.com/channels/940511234179096586) if you like.

**Comment by sergey-tihon** [comment]
I have the same issue
<img width="380" alt="image" src="https://user-images.githubusercontent.com/1197905/154844998-37db8f96-9df5-4026-80ff-1aa933b7a427.png">

and broken link inside error message - https://github.com/fsprojects/fantomas/blob/4.6/docs/Daemon%20mode.md%22%20target=%22_blank

<img width="922" alt="image" src="https://user-images.githubusercontent.com/1197905/154845054-ca41d9d3-e7d2-4943-adeb-234fa1c2ca3b.png">

**Comment by nojaf** [comment]
Closed a bit too earlier, but an update is on its way.
I'll let you know once it was approved.

**Comment by nojaf** [comment]
@AxelJunker could you please try https://plugins.jetbrains.com/plugin/18268-fantomas/versions/stable/159856?

**Comment by sergey-tihon** [comment]
I works for me now, thank you @nojaf !

**Comment by AxelJunker** [comment]
Same here, thank you!
