### ISSUE TITLE
Support Rider EAP version

### ISSUE THREAD

**Issue by sergey-tihon** [nojaf/fantomas-for-rider#4]
Is it hard to allow to use this plugin with Rider EAP?

<img width="950" alt="image" src="https://user-images.githubusercontent.com/1197905/154839918-ade61b13-0dba-4fe3-b7a5-ccfadcb070c5.png">

**Comment by nojaf** [comment]
Hi, probably not, might be as easy as bumping https://github.com/nojaf/fantomas-for-rider/blob/5bcfbcab3cb081511d61ce298a7fa05c10500fdd/src/rider/main/resources/META-INF/plugin.xml#L6

**Comment by nojaf** [comment]
Or removing the until part, I'll check after lunch.

**Comment by sergey-tihon** [comment]
If it is as easy as remove `until-build` then it is nice feature to have, otherwise we may close this issue.

**Comment by nojaf** [comment]
I submitted a new version, I'll let you know once it is available.

**Comment by sergey-tihon** [comment]
I think that there is no need to spent time on this.
Especially because case cool changes are coming https://github.com/JetBrains/resharper-fsharp/pull/339
